[package]
name = "crile-egui"
version = "0.0.0"
edition = "2021"

[dependencies]
egui = "0.26"
hashbrown = "0.14"
glam = "0.25"
crile = { path = "../crile" }
rfd = { version = "0.14", default-features = false, features = [ "gtk3" ] }
pathdiff = "0.2.1"
