[package]
name = "crile-editor"
version = "0.0.0"
edition = "2021"

[dependencies]
egui = "0.28"
glam = "0.28"
log = "0.4"
rfd = "0.14"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
env_logger = "0.11"

crile = { path = "../crile" }
crile-egui = { path = "../crile-egui" }
