[package]
name = "crile-editor"
version = "0.0.0"
edition = "2021"

[dependencies]
egui = "0.26"
egui_dock = "0.11"
glam = "0.25"

crile = { path = "../crile" }
crile-egui = { path = "../crile-egui" }
