[package]
name = "crile"
version = "0.0.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
copypasta = "0.10"
glam = { version = "0.25", features = ["bytemuck"] }
hashbrown = "0.14"
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
log = "0.4"
pollster = "0.3"
wgpu = "0.18"
# TODO: remove this when wgpu updates its rwh version
winit = { version = "0.29", default-features = false, features = ["rwh_05", "x11", "wayland" ] }
env_logger = "0.10"
