[package]
name = "crile"
version = "0.0.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
copypasta = "0.8.2"
glam = { version = "0.24", features = ["bytemuck"] }
hashbrown = "0.14"
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
log = "0.4"
pollster = "0.3"
wgpu = "0.17"
winit = "0.29.1-beta"
env_logger = "0.10"
