[package]
name = "crile"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24"
log = "0.4"
winit = "0.28"

[dev-dependencies]
env_logger = "0.10"
