[package]
name = "crile"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
glam = { version = "0.24", features = ["bytemuck"] }
hashbrown = "0.14.0"
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
log = "0.4"
pollster = "0.3"
thiserror = "1"
wgpu = "0.17"
winit = "0.29.1-beta"

[dev-dependencies]
env_logger = "0.10"
